import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin']
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  robots: {
    index: false,
  }
}

export default function RootLayout({ children }) {
  return (
    <html lang="pl">
      <body className={`body ${inter.variable}`}>{children}</body>
    </html>
  )
}
