export const contentArray = [
  { type: 'HeroBackgroundImg' },
  { type: 'HeroColumn' },
  { type: 'HeroSimple' },
  { type: 'Benefits' },
  { type: 'Faq' },
  { type: 'Opinions' },
  { type: 'TileList' },
  { type: 'CtaSection' },
  { type: 'SimpleCtaSection' },
  { type: 'CourseModules' },
  { type: 'ImageShowcase' },
  { type: 'Bonuses' },
  { type: 'TilesGrid' },
  { type: 'TilesSticky' },
  { type: 'TilesGallery' },
  { type: 'TilesFeatures' },
  { type: 'Community' },
  { type: 'Reviews' },
  { type: 'Introduction' },
  { type: 'ContactForm' },
  { type: 'TabSection' },
  { type: 'TilesIndicated' },
  { type: 'TilesIcon' },
  { type: 'Divider' },
  { type: 'StepList' },
  { type: 'Newsletter' },
  { type: 'CustomerCaseStudy' },
  { type: 'WordsCollection' },
  { type: 'Partners' },
  { type: 'MostPopularCourses' },
  { type: 'LatestBlogEntries' },
  { type: 'CompaniesShowcase' },
  { type: 'TeamShowcase' },
  { type: 'LogoSection' },
];

export default {
  name: 'content',
  type: 'array',
  title: 'Komponenty podstrony',
  of: contentArray,
};
